global:
  qsname: quickstart-atlassian-bitbucket
  owner: quickstart-eng@amazon.com
  marketplace-ami: false
  reporting: true
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
tests:
  bitbucket:
   template_file: quickstart-bitbucket-master.template
   parameter_input: quickstart-bitbucket-master.json
   regions:
    - eu-west-1
